version: "3"

services:
  postgres:
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    ports:
      - 15432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
    postgres:
